source 'https://github.com/CocoaPods/Specs.git'

target 'LEMirroredImagePicker', :exclusive => true do
  pod "LEMirroredImagePicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LEMirroredImagePicker", :path => "../"

  
end
